name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # Cache dependencies (optional)
    - name: Cache node modules
      uses: actions/cache@v3
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    # Install dependencies
    - name: Install Dependencies
      run: npm ci

    # Build the project
    - name: Build Project
      run: npm run build

    # Run tests
    - name: Run Tests
      run: npm test

    # Add deployment steps here if necessary
